"""G-code 生成・プロッタ設定・キャリブレーション。"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pytest

from src.gcode.calibration import build_calibration_gcode, build_pen_z_calibration
from src.gcode.config import PlotterConfig
from src.gcode.generator import GCodeGenerator, simplify_stroke
from src.handwriting.finishing import CONNECT, HANE, HARAI, NONE, TOME

CFG = PlotterConfig()
SQUARE = np.array([[10.0, 10.0], [50.0, 10.0], [50.0, 50.0], [10.0, 50.0], [10.0, 10.0]])
LONG_LINE = np.column_stack([np.linspace(10, 30, 41), np.full(41, 100.0)])
# 簡略化(RDP)で潰れないよう揺らぎのある長い画
WAVY = np.column_stack([np.linspace(10, 30, 81), 100.0 + 0.3 * np.sin(np.linspace(0, 12, 81))])


def _z(line: str) -> float | None:
    m = re.search(r"Z(-?[\d.]+)", line)
    return float(m.group(1)) if m else None


def _feed(line: str) -> int:
    return int(re.search(r"F(\d+)", line).group(1))


def _draws(gcode: list[str]) -> list[str]:
    return [line for line in gcode if line.startswith("G1 X")]


def test_config_is_self_consistent():
    assert f"Z{CFG.pen_down_z}" in CFG.pen_down_command
    assert _z(CFG.pen_up_command) < CFG.finish_lift_z < CFG.pen_down_z


def test_stroke_is_travel_then_pen_down_then_draw():
    gcode = GCodeGenerator().generate([SQUARE, SQUARE + 60])
    assert gcode[:2] == ["; Generated by pen_plotter for xDraw A4", "$H"]
    assert "G92 X0 Y297 Z0" in gcode
    assert gcode.count(CFG.pen_down_command) == 2
    first_down = gcode.index(CFG.pen_down_command)
    assert gcode[first_down - 1].startswith("G0 X10.00 Y10.00")
    assert gcode[first_down + 1].startswith("G1 X50.00 Y10.00")
    assert gcode[-2] == CFG.pen_up_command and gcode[-1].startswith("G0")


def test_empty_input_has_only_header_and_footer():
    assert CFG.pen_down_command not in GCodeGenerator().generate([])


def test_feed_rate_is_slow_at_both_ends_and_fast_in_the_middle():
    feeds = [_feed(line) for line in _draws(GCodeGenerator().generate([SQUARE]))]
    assert feeds[0] < max(feeds) and feeds[-1] < max(feeds)
    uniform = _draws(GCodeGenerator().generate([SQUARE], vary_speed=False))
    assert {_feed(line) for line in uniform} == {int(CFG.draw_speed)}


@pytest.mark.parametrize("finish", [NONE, TOME])
def test_no_z_changes_for_tome_and_none(finish: str):
    draws = _draws(GCodeGenerator().generate([LONG_LINE], finishes=[finish]))
    assert all(_z(line) is None for line in draws)


@pytest.mark.parametrize("finish", [HARAI, HANE])
def test_harai_and_hane_lift_z_at_the_end(finish: str):
    draws = _draws(GCodeGenerator().generate([WAVY], finishes=[finish]))
    zs = [_z(line) for line in draws if _z(line) is not None]
    assert zs and zs == sorted(zs, reverse=True)  # 終端へ向かって単調に持ち上げる
    assert CFG.finish_lift_z <= min(zs) and max(zs) <= CFG.pen_down_z
    assert _z(draws[0]) is None  # 画の頭はしっかり接触


def test_harai_slows_down_while_lifting():
    no_vary = GCodeGenerator().generate([WAVY], finishes=[HARAI], vary_speed=False)
    lifted = [_feed(line) for line in _draws(no_vary) if _z(line) is not None]
    assert set(lifted) == {int(CFG.draw_speed * CFG.harai_speed_factor)}


def test_connection_keeps_pen_down_with_constant_light_contact():
    a = np.array([[0.0, 0.0], [5.0, 0.0]])
    link = np.array([[5.0, 0.0], [5.0, 1.0]])
    b = np.array([[5.0, 1.0], [0.0, 1.0]])
    gcode = GCodeGenerator().generate([a, link, b], finishes=[TOME, CONNECT, TOME])
    assert gcode.count(CFG.pen_down_command) == 1  # つなぎ画と次の画でペンを上げない
    link_z = _z(next(line for line in gcode if line.startswith("G1 X5.00 Y1.00")))
    assert CFG.finish_lift_z < link_z < CFG.pen_down_z
    assert _z(_draws(gcode)[-1]) == CFG.pen_down_z  # 次の画で接触を戻す


def test_generate_indexed_maps_each_stroke_to_its_gcode_lines():
    a = np.array([[0.0, 0.0], [5.0, 0.0]])
    link = np.array([[5.0, 0.0], [5.0, 1.0]])
    b = np.array([[5.0, 1.0], [0.0, 1.0]])
    strokes, finishes = [SQUARE, a, link, b, WAVY], [NONE, TOME, CONNECT, TOME, HARAI]
    gen = GCodeGenerator()
    lines, spans = gen.generate_indexed(strokes, finishes=finishes)
    assert lines == gen.generate(strokes, finishes=finishes)
    assert len(spans) == len(strokes)
    for (start, end), stroke in zip(spans, strokes):
        assert start < end
        # 画の最後の行は終点への描画
        x, y = stroke[-1]
        assert lines[end - 1].startswith(f"G1 X{x:.2f} Y{y:.2f}")
    assert [s for s, _ in spans] == sorted(s for s, _ in spans)
    assert spans[0][0] > lines.index("$H") and spans[-1][1] < len(lines)


def test_simplify_collapses_collinear_points_but_keeps_curves():
    assert len(simplify_stroke(LONG_LINE, 0.05)) == 2
    t = np.linspace(0, np.pi, 50)
    arc = np.column_stack([10 * np.cos(t), 10 * np.sin(t)])
    simplified = simplify_stroke(arc, 0.05)
    assert 2 < len(simplified) < len(arc)
    assert simplify_stroke(arc, 0.0) is arc


def test_save_creates_parent_dirs(tmp_path: Path):
    path = tmp_path / "a" / "b.gcode"
    GCodeGenerator().save(["G90", "G0 X0"], path)
    assert path.read_text() == "G90\nG0 X0\n"


def test_finish_lift_calibration_places_variants_side_by_side():
    gcode = build_calibration_gcode([LONG_LINE], [HARAI], [2.8, 2.2], spacing_mm=30)
    assert gcode.count("$H") == 1
    starts = [line for line in gcode if line.startswith("G0 X")][:-1]
    assert [s.split()[1] for s in starts] == ["X10.00", "X40.00"]
    min_z = [min(_z(line) or 9.0 for line in _draws(part)) for part in _split_at(gcode, "G0 X")]
    assert min_z[0] > min_z[1]
    assert build_calibration_gcode([LONG_LINE], [HARAI], []).count(CFG.pen_down_command) == 0


def test_pen_z_calibration_draws_one_horizontal_line_per_z():
    gcode = build_pen_z_calibration([3.0, 2.0, 1.0])
    draws = [line for line in gcode if line.startswith("G1 X")]
    assert [_z(line) for line in draws] == [3.0, 2.0, 1.0]
    ys = [float(re.search(r"Y([\d.]+)", line).group(1)) for line in draws]
    assert ys == sorted(ys, reverse=True)


def _split_at(gcode: list[str], prefix: str) -> list[list[str]]:
    parts: list[list[str]] = []
    for line in gcode:
        if line.startswith(prefix):
            parts.append([])
        if parts:
            parts[-1].append(line)
    return [p for p in parts if any(line.startswith("G1 X") for line in p)]
