"""src/plotter_gui/preview.py の単体テスト。

preview は Tkinter に依存しない純粋関数群。G-code 文字列/ファイルを
ストローク列に分解し、matplotlib Axes に描画できることを検証する。
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

# ヘッドレス環境 (CI/WSL) でも import 可能にする。
# Tk バックエンドが選ばれないよう Agg を明示する。
matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402

from src.plotter_gui.preview import Stroke, parse_gcode, render_strokes  # noqa: E402


# xDraw A4 ヘッダ (src/gcode/generator.py と同等)。
# parse_gcode はこれらをすべて読み飛ばす必要がある。
_HEADER = "; Generated by pen_plotter for xDraw A4\n$H\nG4 P1\nG92 X0 Y297 Z0\nG90\n"
_FOOTER = "G0 X5 Y292 F5000\n"


class TestParseGcode:
    def test_parse_gcode_simple_two_strokes(self) -> None:
        # G0 → 新規ストロークの開始 (起点保持) / G1 → 同ストロークの続き
        # の最小ケース。2 ストロークが分離されること。
        source = (
            _HEADER
            + "G0 X10 Y10 F5000\n"
            + "G1 X20 Y20 F1000\n"
            + "G0 X50 Y50 F5000\n"
            + "G1 X60 Y60 F1000\n"
            + _FOOTER
        )
        strokes = parse_gcode(source)
        # フッターも G0 だが点が 1 つしかないため空ストロークとして除外される。
        assert len(strokes) == 2
        assert strokes[0].points == [(10.0, 10.0), (20.0, 20.0)]
        assert strokes[1].points == [(50.0, 50.0), (60.0, 60.0)]

    def test_parse_gcode_skips_z_axis(self) -> None:
        # ペン制御 (Z 軸) は座標を持たないため X/Y を継承せず無視される。
        source = (
            _HEADER
            + "G0 X10 Y10 F5000\n"
            + "G1G90 Z3.5 F5000\n"  # ペンダウン
            + "G1 X20 Y20 F1000\n"
            + "G1G90 Z0.5 F5000\n"  # ペンアップ
            + _FOOTER
        )
        strokes = parse_gcode(source)
        assert len(strokes) == 1
        # Z 軸行は完全に無視。座標として (0, 3.5) などになっていないこと。
        assert strokes[0].points == [(10.0, 10.0), (20.0, 20.0)]

    def test_parse_gcode_skips_comments_and_header(self) -> None:
        # コメント / ホーミング / 座標系設定を含む先頭ヘッダを完全スキップ。
        source = "; comment line\n$H\nG4 P1\nG92 X0 Y297 Z0\nG90\nG0 X1 Y2 F5000\nG1 X3 Y4 F1000\n"
        strokes = parse_gcode(source)
        assert len(strokes) == 1
        # ヘッダの G92 X0 Y297 が起点として混ざらないこと。
        assert strokes[0].points == [(1.0, 2.0), (3.0, 4.0)]

    def test_parse_gcode_inherits_previous_xy(self) -> None:
        # GRBL モード仕様: X だけ / Y だけの行は前回値を継承する。
        # プレビューでも同じ仕様を再現しないと座標が壊れる。
        source = (
            "G0 X10 Y10 F5000\n"
            "G1 X20\n"  # Y=10 を継承 → (20, 10)
            "G1 Y30\n"  # X=20 を継承 → (20, 30)
        )
        strokes = parse_gcode(source)
        assert len(strokes) == 1
        assert strokes[0].points == [(10.0, 10.0), (20.0, 10.0), (20.0, 30.0)]

    def test_parse_gcode_from_path(self, tmp_path: Path) -> None:
        # 実用ケース: ファイルパスを受け取って読み込めること。
        gcode_file = tmp_path / "sample.gcode"
        gcode_file.write_text("G0 X0 Y0 F5000\nG1 X10 Y0 F1000\nG1 X10 Y10 F1000\n")
        strokes = parse_gcode(gcode_file)
        assert len(strokes) == 1
        assert strokes[0].points == [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0)]

    def test_parse_gcode_drops_single_point_strokes(self) -> None:
        # G0 単独 (= 移動するだけで描画しない) は空ストロークとして除外。
        source = "G0 X10 Y10 F5000\nG0 X50 Y50 F5000\nG1 X60 Y60 F1000\n"
        strokes = parse_gcode(source)
        # 最初の G0 は単独 (描画なし) → 除外。2 番目の G0 + G1 のみ生き残る。
        assert len(strokes) == 1
        assert strokes[0].points == [(50.0, 50.0), (60.0, 60.0)]

    def test_stroke_is_frozen_dataclass(self) -> None:
        # frozen にしないと UI スレッド ↔ render 関数で渡し回した際に
        # 不意の改変で再描画が壊れる。
        s = Stroke(points=[(0.0, 0.0), (1.0, 1.0)])
        import dataclasses

        with pytest.raises(dataclasses.FrozenInstanceError):
            s.points = []  # type: ignore[misc]


class TestRenderStrokes:
    def test_render_strokes_runs_without_error(self) -> None:
        # matplotlib バックエンドが Agg なのでウィンドウは出ない。
        # 例外なく実行できることだけを保証する smoke テスト。
        fig, ax = plt.subplots()
        try:
            strokes = [
                Stroke(points=[(0.0, 0.0), (10.0, 10.0)]),
                Stroke(points=[(20.0, 20.0), (30.0, 30.0), (40.0, 25.0)]),
            ]
            render_strokes(ax, strokes)
        finally:
            plt.close(fig)

    def test_render_strokes_handles_empty_list(self) -> None:
        # ファイル選択前 / G-code パース失敗時に空リストが渡る経路があるため
        # 例外なく描画できる必要がある (枠だけ表示)。
        fig, ax = plt.subplots()
        try:
            render_strokes(ax, [])
        finally:
            plt.close(fig)


import pytest  # noqa: E402  (conftest 経由ではなく明示 import)
