import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt

from src.gcode.config import PlotterConfig


# ストローク = (N, 2) の numpy配列。各行は (x, y) 座標 (mm)
Stroke = npt.NDArray[np.float64]


class GCodeGenerator:
    """ストローク列からxDraw A4用G-codeを生成する"""

    def __init__(self, config: PlotterConfig | None = None) -> None:
        self.config = config or PlotterConfig()

    def _format_coord(self, value: float) -> str:
        return f"{value:.{self.config.decimal_places}f}"

    def _header(self) -> list[str]:
        """ホーミング + 座標系設定 + ペンアップ"""
        lines = [
            "; Generated by pen_plotter for xDraw A4",
            "$H",
            "G4 P1",
            f"G92 X0 Y{self.config.paper_height:.0f} Z0",
            "G90",
            self.config.pen_up_command,
        ]
        return [l for l in lines if l]

    def _footer(self) -> list[str]:
        """ペンアップ + ホーム付近に移動"""
        return [
            self.config.pen_up_command,
            f"G0 X5 Y{self.config.paper_height - 5:.0f} F{self.config.travel_speed:.0f}",
        ]

    def _compute_feed_rate(self, t: float) -> int:
        """S字フィードレート: 始点・終点で0.7倍、中盤で1.3倍"""
        factor = 0.7 + 0.6 * math.sin(math.pi * t)
        return int(self.config.draw_speed * factor)

    def _stroke_to_gcode(
        self, stroke: Stroke, vary_speed: bool = True
    ) -> list[str]:
        """単一ストロークをG-codeに変換"""
        if len(stroke) < 2:
            return []

        lines: list[str] = []
        x0, y0 = stroke[0]
        lines.append(
            f"G0 X{self._format_coord(x0)} Y{self._format_coord(y0)} F{self.config.travel_speed:.0f}"
        )
        lines.append(self.config.pen_down_command)
        delay = self.config.pen_delay_gcode()
        if delay:
            lines.append(delay)

        n_draw_points = len(stroke) - 1
        for i, point in enumerate(stroke[1:]):
            x, y = point
            if vary_speed and n_draw_points > 1:
                t = i / (n_draw_points - 1)
                feed = self._compute_feed_rate(t)
            else:
                feed = self.config.draw_speed
            lines.append(
                f"G1 X{self._format_coord(x)} Y{self._format_coord(y)} F{feed:.0f}"
            )
        lines.append(self.config.pen_up_command)
        if delay:
            lines.append(delay)

        return lines

    def generate(
        self, strokes: list[Stroke], vary_speed: bool = True
    ) -> list[str]:
        """ストローク列からG-code全体を生成"""
        lines = self._header()
        for stroke in strokes:
            lines.extend(self._stroke_to_gcode(stroke, vary_speed=vary_speed))
        lines.extend(self._footer())
        return lines

    def save(self, gcode_lines: list[str], filepath: str | Path) -> None:
        """G-codeをファイルに保存"""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text("\n".join(gcode_lines) + "\n", encoding="utf-8")
