from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt

from src.gcode.config import PlotterConfig


# ストローク = (N, 2) の numpy配列。各行は (x, y) 座標 (mm)
Stroke = npt.NDArray[np.float64]


class GCodeGenerator:
    """ストローク列からG-codeを生成する"""

    def __init__(self, config: PlotterConfig | None = None) -> None:
        self.config = config or PlotterConfig()

    def _format_coord(self, value: float) -> str:
        """座標値をフォーマット"""
        return f"{value:.{self.config.decimal_places}f}"

    def _header(self) -> list[str]:
        """G-codeヘッダー: 絶対座標、mm単位、ペンアップ"""
        return [
            "; Generated by pen_plotter",
            "G90",
            "G21",
            self.config.pen_up_command,
            self.config.pen_delay_gcode(),
            f"G0 F{self.config.travel_speed:.0f}",
        ]

    def _footer(self) -> list[str]:
        """G-codeフッター: ペンアップ、原点復帰"""
        return [
            self.config.pen_up_command,
            self.config.pen_delay_gcode(),
            "G0 X0 Y0",
            "M2",
        ]

    def _compute_feed_rate(self, t: float) -> float:
        """ストローク内位置 t (0→1) に応じたフィードレートをS字カーブで計算

        ベル型カーブ: 始点・終点で0.7倍、中盤で1.3倍に滑らかに変化
        """
        import math

        factor = 0.7 + 0.6 * math.sin(math.pi * t)
        return int(self.config.draw_speed * factor)

    def _stroke_to_gcode(
        self, stroke: Stroke, vary_speed: bool = True
    ) -> list[str]:
        """単一ストロークをG-codeに変換"""
        if len(stroke) < 2:
            return []

        lines: list[str] = []
        x0, y0 = stroke[0]
        lines.append(
            f"G0 X{self._format_coord(x0)} Y{self._format_coord(y0)}"
        )
        lines.append(self.config.pen_down_command)
        lines.append(self.config.pen_delay_gcode())

        n_draw_points = len(stroke) - 1
        for i, point in enumerate(stroke[1:]):
            x, y = point
            if vary_speed and n_draw_points > 1:
                t = i / (n_draw_points - 1)
                feed = self._compute_feed_rate(t)
            else:
                feed = self.config.draw_speed
            lines.append(
                f"G1 X{self._format_coord(x)} Y{self._format_coord(y)} F{feed:.0f}"
            )
        lines.append(self.config.pen_up_command)
        lines.append(self.config.pen_delay_gcode())

        return lines

    def generate(
        self, strokes: list[Stroke], vary_speed: bool = True
    ) -> list[str]:
        """ストローク列からG-code全体を生成"""
        lines = self._header()
        for stroke in strokes:
            lines.extend(self._stroke_to_gcode(stroke, vary_speed=vary_speed))
        lines.extend(self._footer())
        return lines

    def save(self, gcode_lines: list[str], filepath: str | Path) -> None:
        """G-codeをファイルに保存"""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text("\n".join(gcode_lines) + "\n", encoding="utf-8")
